name: rentapp
description: Technical Test for Double V Partners
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.0.0
  intl: ^0.18.1
  rentapp_ui:
    path: packages/rentapp_ui
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  slang_build_runner: ^3.25.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#232323"
  android: true
  ios: true
