include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    public_member_api_docs: false
    one_member_abstracts: false
analyzer:
  errors:
    unused_import: error
    invalid_annotation_target: ignore
    sort_pub_dependencies: ignore
    avoid_renaming_method_parameters: ignore
    type_annotate_public_apis: ignore
