name: rentapp_ui
description: My new Flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  lottie: ^2.7.0
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/gen/

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/svgs/
    - assets/icons/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: lib/src/typography/fonts/JosefinSans-Regular.ttf
        - asset: lib/src/typography/fonts/JosefinSans-Medium.ttf
        - asset: lib/src/typography/fonts/JosefinSans-SemiBold.ttf
        - asset: lib/src/typography/fonts/JosefinSans-Bold.ttf

    - family: RentAppIcons
      fonts:
        - asset: assets/icons/RentAppIcons.ttf
