name: rentapp_slang
description: My new Dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
dependencies:
  path: ^1.8.3
